// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBovlCbLcJJHLrMW5aG9kNpZazZW7Fu_s8',
    appId: '1:289795924894:web:f52e9306984373c2d96c8f',
    messagingSenderId: '289795924894',
    projectId: 'whatsappbyck',
    authDomain: 'whatsappbyck.firebaseapp.com',
    databaseURL: 'https://whatsappbyck-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whatsappbyck.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9ukouc1eahdI1bMPhQQkR_dE9Unc3kBI',
    appId: '1:289795924894:android:bff7bedee0d1707ad96c8f',
    messagingSenderId: '289795924894',
    projectId: 'whatsappbyck',
    databaseURL: 'https://whatsappbyck-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whatsappbyck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqsEOd5zj6jk93NnryfH2l9Bf_lWJdTFo',
    appId: '1:289795924894:ios:34f75956a48c6ea6d96c8f',
    messagingSenderId: '289795924894',
    projectId: 'whatsappbyck',
    databaseURL: 'https://whatsappbyck-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whatsappbyck.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBovlCbLcJJHLrMW5aG9kNpZazZW7Fu_s8',
    appId: '1:289795924894:web:84e58d6d35ce0ff4d96c8f',
    messagingSenderId: '289795924894',
    projectId: 'whatsappbyck',
    authDomain: 'whatsappbyck.firebaseapp.com',
    databaseURL: 'https://whatsappbyck-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whatsappbyck.appspot.com',
  );
}
